#!/bin/sh -e

. /usr/share/debconf/confmodule


# configure ?
db_input medium serweb/config || true
db_go

db_get serweb/config

if [ "$RET" = "false" ]; then
  exit 0
fi

db_input medium serweb/cron_daily || true
db_go

db_input medium serweb/cron_sync || true
db_go

