#!/bin/sh -e

. /usr/share/debconf/confmodule


# configure ?
db_input medium serweb/config || true
db_go

db_get serweb/config

if [ "$RET" = "false" ]; then
  exit 0
fi

db_input medium serweb/cron_daily || true
db_go

db_input medium serweb/cron_sync || true
db_go

db_input medium serweb/apacheconfig || true
db_go

db_input medium serweb/apacheenable || true
db_go

db_input medium serweb/removeapache || true
db_go

db_input medium serweb/SERVERNAME || true
db_go

db_input medium serweb/DB_HOST || true
db_go

db_input medium serweb/DB_PORT || true
db_go

db_input medium serweb/DB_NAME || true
db_go

db_input medium serweb/DB_USER || true
db_go

db_input medium serweb/DB_PASS || true
db_go

db_input medium serweb/PROXIES || true
db_go

db_input medium serweb/RPC_PORT || true
db_go

db_input medium serweb/STRIPNAME || true
db_go


